[build]
  publish = "."
  command = "# No build needed - static HTML"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self' https://api.netlify.com"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Form spam protection
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = true
[build.processing.js]
  bundle = false
  minify = true
[build.processing.html]
  pretty_urls = true
  minify = true

# Redirect rules (if needed later)
# [[redirects]]
#   from = "/old-path"
#   to = "/new-path"
#   status = 301